### PR TITLE
Ui repairings

### LINKED ISSUE #83: Implement clear-all button

### LINKED ISSUE #84: Rearrange buttons
Eliminate dead buttons (except for the sprinkler, clear-all and state-change). State-change and clear-all don't need the extra menu step.

### LINKED ISSUE #92: Drawing artifacts
I found a way to trigger some weird drawing. 
artifact
Dropping a new color drop exactly on the boundary of another drop of the same color produces a hard edge. This happens most likely because no actual new drop will be generated (due to the same color). The vertex insertion will than take place when actually dropping a new color drop. Until than the edge stays like this. 

I think a good fix would be to check vertex distances in each case in `addDrop`.

### LINKED ISSUE #99: Visualize custom rakes
* user should only input in 1/100 ticks

### LINKED ISSUE #104: Fix Pallet
Palette doesn't save when storage is disabled

### PR DESCRIPTION
**Pull request by JBenda**
* [x] repair session storage for pallet
* [x] remove not needed buttons
* [x] rearrange UI
* [x] change sidebar colors
* [x] sidebar UI tweaks
* [x] rakes now look like the given placement

### CODE REVIEW

**Review by t-erxleben — CHANGES_REQUESTED** [review]
Maybe the space between buttons and canvas is a little too big now :'D
Overall the rework looks good and I like the slower color dropping. I'm not a fan of the colors to be honest but that's personal taste.

One problem I found was laggy behavior for a short period of time after clearing the screen.

**Comment by JBenda** [comment]
The colors are now easy to change
this are 5 colors defined for the web.

I will take a look if I find the lag too

**Comment by JBenda** [comment]
Can you test it again? I think the 'lag' is "just" a slightly larger time step, which  feels with the huge slope at the beginning of the root function to a laggy feeling. I now replaced the first part of the function with a linear curve to let at feel less explosive.

**Review by t-erxleben — APPROVED** [review]
:+1:

**Pull request merged**
