### PR TITLE
UI fixes

### LINKED ISSUE #21: Fix Rake tool tips
* curve for curve tool has a break at begin
* rake line displayed wrong
* pattern is regenerated every time(do this only on change)

### LINKED ISSUE #24: UI fixes
* [x] rake bullet should scale with canvas
* [x] back to color mode icon new
* [x] tooltip line for rake should cover whole image
* [x] snaps to perpendicular angle
* [x] line with arrow to indicate "draw speed"
* [x] disable selectable button

### LINKED ISSUE #27: UI - Download button
download button of canvas

### LINKED ISSUE #31: Website title should be Marbellous
As described in the title. Current name is 'Marbeling'.

### LINKED ISSUE #36: Circle does not stop growing
Color dropping does not stop when the mouse button goes up outside of the canvas.

### PR DESCRIPTION
**Pull request by JBenda**
solves multiple ui problems

### CODE REVIEW

**Review by t-erxleben — CHANGES_REQUESTED** [review]
Arrowheads of rake tool tips don't work in Chrome.  For some reason circles are drawn instead.

**Comment by t-erxleben** [comment]
Maybe less empty space above the headline would look better. But that's just my opinion, so feel free to ignore this :D

**Comment by JBenda** [comment]
In my Chrome version it's drawn as intended. I found a possible cause, can you please check :)

**Review by t-erxleben — APPROVED** [review]
nice :)

**Pull request merged**
