### PR TITLE
feature/#138 ui tweaks

### LINKED ISSUE #138: UI tweaks
## Please add further UI problems to this list:

* [x] write help text
* [x] sidebar should open constituent
* [x] space between option headers and options is not the same size for every option type
* [x] some reference size is needed for free value input
* [x] defaults should be visible in options
* [x] set resolution options to multiples of 500(?)
* [x] "clear canvas" should be below "one step back" in rake state
* [x] rename "placement" to "gap"
* [x] rename period to period
* [x] pallet to palette
* [x] typos !
* [x] default wavy rake settings should be sufficient for tileable images (e.g. magnitude and period)
* [x] allow larger periods for wavy rake?
* [x] make local sprinkle default

### LINKED ISSUE #175: Remove 'Note' directory
It is out dated and not needed any more.

### PR DESCRIPTION
**Pull request by JBenda**
- Add sliders to sprinkler uis, magnitude and period
- Add nice CSS for slider
- Set default values for sprinkler on delete
- Add disabled function to sigma slider
- Fix to large sprinkle drops
- Adapt sample rate for wave rake to period
- Add defaults for text inputs
- Add help popup
- Selecting Sprinkler will not open sidebar any more
- Fix spacing in sidebar menu 

close #138

### CODE REVIEW

**Comment by JBenda** [comment]
The help text is still missing, but the UI is there

**Comment by t-erxleben** [comment]
Looks great! :D
However it is still possible to scroll down some pixels.
To be consistent with the switches it would be better to have round slider handles imo.

Example for scrolling:
image

**Comment by t-erxleben** [comment]
I could rework the text fields in this branch if you are okay with it @JBenda ?

**Comment by JBenda** [comment]
Sure :+1

**Comment by JBenda** [comment]
I can't recreate the scrolling on my setup, we can debug it in the next meeting.

**Review by t-erxleben — APPROVED** [review]
:+1:

**Review by dknigs — APPROVED** [review]
👍

**Pull request merged**
