### PR TITLE
Raking for front end and screen resolution handling

### LINKED ISSUE #62: Provide defaults
Currently front end needs to ensure proper initialization. Maybe we should introduce some defaults (e.g. for a color palette).

### LINKED ISSUE #100: Save screen resolution in settings
Screen resolution should be saved in options singleton. There should be 2 versions. One for polygon view and the second (higher) one for screenshots and raking.

### LINKED ISSUE #110: Add method to change screen resolution in WGLContext

### LINKED ISSUE #111: Make raking possible via interface
Implement the front end facing rake call.

### LINKED ISSUE #112: Introduce proper state switching
It should be possible to switch from color dropping to raking and back without breaking everything.

### LINKED ISSUE #116: use `initWGL` in frontend
* [ ] change `initWGL` signature to be every time square
* [ ] implement initWGL

### LINKED ISSUE #117: Download for raked images
Screenshots of raked images need to be done with the rake renderer.

### PR DESCRIPTION
**Pull request by t-erxleben**
closes #100 closes #62 closes #110 closes #112 closes #117 closes #111 closes #116
While working I realized that all these problems are relatively close related so this PR got a little unspecific.

### CODE REVIEW

**Comment by t-erxleben** [comment]
It seems like providing color defaults (setting a palette in options constructor) breaks the way the front end initializes color stuff. At least drops were only black. That's why it's commented right now.

Hard coded canvas sizes still need to be replaced.

**Comment by t-erxleben** [comment]
Apparently raking breaks if the project is not build in debug mode. Problem seems to be inside the front end facing call.

**Comment by t-erxleben** [comment]
Well I probably found the reason for #118. It seems like `GLuint` is bigger than the type coming from front end. That would explain the random numbers after the first 1 (because of misaligned data) and the buffer that was too small to actually write 1000 `GLuint`.

**Review by JBenda — APPROVED** [review]
Nice, the Color error by downloading will I investigate in #125 after merge

**Pull request merged**
