### PR TITLE
Add UI for resizing

### LINKED ISSUE #154: Resolution option for users
We need a dropdown menu to let users choose the resolution.

### PR DESCRIPTION
**Pull request by JBenda**
Add new sidebar entry in General

close #154

### CODE REVIEW

**Review by t-erxleben — CHANGES_REQUESTED** [review]
Nice work but I have two points to discuss:
- Help should still be the first entry in the side bar imo. 
- After changing the resolution the UI should change to drop state (at least that's what the backend does right now). We could also stay in the current state but that would require a little change in the backend. I would be fine with both solutions however we need to agree on one :smile:

**Comment by JBenda** [comment]
First point: true ^^
second point because we clean everything, it should be more intuitive to go back to the drop state

**Comment by t-erxleben** [comment]
Changing the resolution in rake state and switching to rake state afterwards breaks the UI by somehow deleting the rake button.

image

**Review by t-erxleben — APPROVED** [review]
:+1:
I fixed the resizing problem in #161 :)

**Pull request merged**
